#!/usr/bin/env bash
# Refresh the Safari (Xcode) wrapper from the current extension source.
#
#   pnpm --filter @geld/extension safari:sync
#
# 1. builds the Safari flavour of the extension (wxt build -b safari --mv3)
# 2. copies it over the extension's Resources folder inside the Xcode project
#    generated by `safari:project`
# 3. sets the Xcode MARKETING_VERSION to the version in package.json and bumps
#    CURRENT_PROJECT_VERSION (the App Store build number) by one
#
# Run it before every archive. Works on macOS and Linux (CI); the archive itself needs Xcode.
set -euo pipefail

cd "$(dirname "$0")/.."

PROJECT_DIR="safari/Geld"
PBXPROJ="$PROJECT_DIR/Geld.xcodeproj/project.pbxproj"
if [[ ! -f "$PBXPROJ" ]]; then
  echo "No Xcode project at $PROJECT_DIR. Run 'pnpm --filter @geld/extension safari:project' first." >&2
  exit 1
fi

pnpm run build:safari

# The converter (with --copy-resources) keeps the web extension here; the folder
# name differs slightly between converter versions, so find it.
RESOURCES="$(find "$PROJECT_DIR" -type d -name Resources -path '*Extension*' -not -path '*/build/*' | head -n 1)"
if [[ -z "$RESOURCES" ]]; then
  echo "Could not find the extension Resources folder under $PROJECT_DIR." >&2
  exit 1
fi
rsync -a --delete .output/safari-mv3/ "$RESOURCES/"
echo "Copied .output/safari-mv3 -> $RESOURCES"

VERSION="$(node -p "require('./package.json').version")"
CURRENT_BUILD="$(sed -n 's/.*CURRENT_PROJECT_VERSION = \([0-9]*\);.*/\1/p' "$PBXPROJ" | head -n 1)"
# CI passes its run number so every upload has a unique, increasing build number;
# locally we bump the committed value by one.
if [[ "${GELD_BUILD_NUMBER:-}" =~ ^[0-9]+$ ]]; then
  NEXT_BUILD="$GELD_BUILD_NUMBER"
else
  NEXT_BUILD=$(( ${CURRENT_BUILD:-0} + 1 ))
fi
# Every target shares one version and one build number.
# BSD and GNU sed disagree about -i; write through a temp file instead.
sed -E "s/MARKETING_VERSION = [^;]+;/MARKETING_VERSION = $VERSION;/g; s/CURRENT_PROJECT_VERSION = [0-9]+;/CURRENT_PROJECT_VERSION = $NEXT_BUILD;/g" "$PBXPROJ" > "$PBXPROJ.tmp" && mv "$PBXPROJ.tmp" "$PBXPROJ"
echo "Xcode version $VERSION, build $NEXT_BUILD"

# In CI the refreshed wrapper is archived straight away and never committed.
if [[ -n "${CI:-}" ]]; then exit 0; fi

# The wrapper is tracked: the copied build and the bumped build number must land in git,
# otherwise the next sync bumps from the wrong base and the archive drifts from main.
echo
echo "Changed files to commit:"
git -C "$(git rev-parse --show-toplevel)" status --short -- apps/extension/safari | sed 's/^/  /'
echo
echo "Next:"
echo "  git add apps/extension/safari && git commit -m 'Safari: sync wrapper with $VERSION (build $NEXT_BUILD)' && git push"
echo "  pnpm safari:open  ->  Product > Archive  ->  Distribute App > App Store Connect"
